### ISSUE TITLE
React-Mobx binding example

### ISSUE THREAD

**Issue by tripolskypetr** [ixrock/mobx-observable-history#6]
This library is damn nice! But it completely too low-level for React UI development. The router component is required for business-oriented solutions. As you can see, I created a new pull request which provides the new code sample in Readme file. The pull request is waiting for your review

```tsx
import { createObservableHistory } from "mobx-observable-history"
import { Switch } from 'react-history-switch';

...

const routerService = createObservableHistory();

...

const items = [
  {
    path: '/',
    redirect: '/home',
  },
  {
    path: '/home',
    component: HomePage,
  },
  {
    path: '/next/:param',
    component: NextPage,
  },
];

...

<Switch history={routerService} items={items} />
```

@ixrock

https://github.com/ixrock/mobx-observable-history/pull/5

**Comment by ixrock** [comment]
Why it's low level for React devs? 
It's replacement for vanilla `history` to be used with react router as `<Router history={observableHistory}>...</Router>`. 
Your suggestion seems like promoting `react-history-switch` package or I miss something? :)

**Comment by tripolskypetr** [comment]
Actually, It is) Before this act of promotion I used BrowserRouter (This one is not giving any access to history instance) and didn't notice the history param in Router component
